---
- name: count the docker containers present
  shell: docker ps -aq|wc -l
  register: countainers
  changed_when: no

- name: ensure no docker containers present
  shell: docker stop $(docker ps -a -q); docker rm -f $(docker ps -a -q)
  when: countainers.stdout != '0'

- name: start selenium hub
  docker_container:
    name: selenium-hub
    image: "selenium/hub:latest"
    state: started
    ports: "{{ hub_port }}:4444"
    env:
      #GRID_DEBUG: true
      GRID_MAX_SESSION: "{{ hub_max_session }}"

- name: verify hub is up
  wait_for:
    delay: 5
    host: "{{ inventory_hostname }}"
    port: "{{ hub_port }}"
  tags:
    - test

- name: Set hub_host fact
  set_fact:
    hub_host: "{{ inventory_hostname }}:{{ hub_port }}"
