---
- name: Set initial facts
  set_fact:
    remote_run: false
    workspace: "{{ ansible_env.WORKSPACE | default(playbook_dir) }}"

- name: Find AWS region in different env variables
  set_fact:
    aws_region: "{{ lookup('env', item, default=omit) }}"
  with_items:
    - AWS_REGION
    - EC2_REGION
    - AWS_DEFAULT_REGION
  when:
    - ansible_env.AWS_ACCESS_KEY_ID is defined and ansible_env.AWS_ACCESS_KEY_ID != ''
    - ansible_env.AWS_SECRET_ACCESS_KEY is defined and ansible_env.AWS_SECRET_ACCESS_KEY != ''

- name: fail the play if the previous command did not succeed
  fail:
    msg: "Missing REGION env variable, following names are accepted: AWS_REGION or EC2_REGION or AWS_DEFAULT_REGION"
  when: aws_region is defined and aws_region == ''

- name: Set settings file name
  set_fact:
    settings_file: "settings_{{ aws_region | default('localhost') | lower }}.yml"

- name: set aws credentials
  set_fact:
    aws_vars:
      AWS_REGION: "{{ aws_region }}"
      AWS_ACCESS_KEY_ID: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
    remote_run: true
  no_log: true
  when:
    - ansible_env.AWS_ACCESS_KEY_ID is defined and ansible_env.AWS_ACCESS_KEY_ID != ''
    - ansible_env.AWS_SECRET_ACCESS_KEY is defined and ansible_env.AWS_SECRET_ACCESS_KEY != ''
    - aws_region is defined and aws_region != ''