# For testing purpose only!
node_group:
  hosts:
    ubuntu:
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: ubuntu

hub_group:
  hosts:
    amazon-linux-2:
      ansible_python_interpreter: /usr/bin/python
      ansible_user: ec2-user

router_group:
  hosts:
    router1:
