---
grid_router_version: 1.6.7 # https://hub.docker.com/r/aerokube/ggr/tags
grid_router_ui_version: 1.1.2 # https://hub.docker.com/r/aerokube/ggr-ui/tags
selenoid_ui_version: 1.10.0 # https://hub.docker.com/r/aerokube/selenoid-ui/tags/
grid_router_path: /etc/grid-router # Path to GridRouter
grid_router_qouta_path: /etc/grid-router/quota # Path to GridRouter quota
grid_router_qouta_user: selenium # GridRouter quota user
grid_router_time_zone: Europe/Prague # Timezone in container
grid_router_port: 4444 # GridRouter port
grid_router_sctl_version: 1.2.0 # sctl version — https://github.com/seleniumkit/sctl/releases
grid_router_host_list: group # Host list for selenium.xml
grid_router_timeout: 5m0s

grid_router_regions: # Hosts list per region
  - name: "eu-central-1"
    hosts:
      - name: localhost
        port: 4444
        browser_count: 5

grid_router_browsers: # Browser list usage selenoid
  - name: "firefox"
    defaultVersion: "59.0"
    versions:
      - "59.0"
      - "58.0"
      - "57.0"
  - name: "chrome"
    defaultVersion: "65.0"
    versions:
      - "65.0"
      - "64.0"
      - "63.0"
  - name: "opera"
    defaultVersion: "52.0"
    versions:
      - "52.0"
      - "51.0"
      - "50.0"
