---
- name: Ensure all failed instances are tagged as FAILED
  ec2_tag:
    resource: "{{ hostvars[item].ec2_all_facts.instance_id }}"
    state: present
    tags:
      Name: "{{ hostvars[item].ec2_all_facts.tags.Name }}-FAILED"
      Type: "FAILED"
  delegate_to: localhost
  with_items: "{{ groups.all }}"
  register: retagging_complete
  when: hostvars[item].ec2_all_facts is defined

- debug: var=retagging_complete

- name: Get instance facts
  ec2_instance_facts:
    filters:
      instance-id: "{{ item.split(',') | first }}"
  register: ec2_facts
  delegate_to: localhost
  delegate_facts: True
  with_lines: cat "{{ hostvars['localhost'].workspace }}/ec2_instances.txt"
  when: not retagging_complete.changed | bool

- name: Ensure all failed instances are tagged as FAILED
  ec2_tag:
    resource: "{{ item.instances[0].instance_id }}"
    state: present
    tags:
      Name: "{{ item.instances[0].tags.Name }}-FAILED"
      Type: "FAILED"
  delegate_to: localhost
  with_items: "{{ ec2_facts.results }}"
  when: not retagging_complete.changed | bool