- name: Set credentials
  hosts: localhost
  gather_facts: yes
  tags:
    - always
  tasks:
    - name: Prepare credentials
      include_role:
        name: common
        tasks_from: setup_credentials

- name: Clean up ec2 instances
  hosts: localhost
  gather_facts: yes
  tags:
    - ec2
  environment: "{{ aws_vars }}"
  pre_tasks:
    - name: include vars
      include_vars: "{{ settings_file }}"
  tasks:
    - name: Cancel spot requests
      script: "cancel_spot_instance_requests.py --spot-ids {{ item.split(',')[1] }}"
      register: response
      with_lines: cat "{{ workspace }}/ec2_instances.txt"
      when: request_spot_instance | bool
      ignore_errors: True

    - name: Terminate instances by ids from file
      ec2:
        state: 'absent'
        instance_ids: "{{ item.split(',') | first }}"
      with_lines: cat "{{ workspace }}/ec2_instances.txt"
